"""empty message

Revision ID: 238c0a79ea3d
Revises: 88f9b1d137a3
Create Date: 2020-01-28 15:46:42.732945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238c0a79ea3d'
down_revision = '88f9b1d137a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
