"""empty message

Revision ID: 417900896c6d
Revises: 94e948ba8b30
Create Date: 2020-02-06 20:09:17.273771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417900896c6d'
down_revision = '94e948ba8b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
