"""empty message

Revision ID: 492ec352a608
Revises: 5d8bb7ea5b77
Create Date: 2020-01-26 19:55:09.532161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '492ec352a608'
down_revision = '5d8bb7ea5b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(length=1600), nullable=False))
    op.add_column('projects', sa.Column('images', sa.String(length=120), nullable=False))
    op.add_column('projects', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_index('email', table_name='projects')
    op.drop_index('username', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['images'])
    op.drop_column('projects', 'username')
    op.drop_column('projects', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('projects', sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('username', 'projects', ['username'], unique=True)
    op.create_index('email', 'projects', ['email'], unique=True)
    op.drop_column('projects', 'name')
    op.drop_column('projects', 'images')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
