"""empty message

Revision ID: 88f9b1d137a3
Revises: d37f95fbed3a
Create Date: 2020-01-26 23:19:34.971386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f9b1d137a3'
down_revision = 'd37f95fbed3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soft_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('skillImage', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soft_skills')
    # ### end Alembic commands ###
