"""empty message

Revision ID: 94e948ba8b30
Revises: a69843d30b21
Create Date: 2020-02-05 16:29:31.436337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e948ba8b30'
down_revision = 'a69843d30b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=1600), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('about', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'about', 'user', ['user_id'], ['id'])
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'user', ['user_id'], ['id'])
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'user', ['user_id'], ['id'])
    op.add_column('soft_skills', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'soft_skills', 'user', ['user_id'], ['id'])
    op.add_column('tech_skills', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tech_skills', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tech_skills', type_='foreignkey')
    op.drop_column('tech_skills', 'user_id')
    op.drop_constraint(None, 'soft_skills', type_='foreignkey')
    op.drop_column('soft_skills', 'user_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'user_id')
    op.drop_constraint(None, 'about', type_='foreignkey')
    op.drop_column('about', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
