"""empty message

Revision ID: a69843d30b21
Revises: 2d22ff051156
Create Date: 2020-01-28 18:01:33.876620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69843d30b21'
down_revision = '2d22ff051156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('resume', sa.String(length=60), nullable=False))
    op.create_unique_constraint(None, 'about', ['resume'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'about', type_='unique')
    op.drop_column('about', 'resume')
    # ### end Alembic commands ###
