"""empty message

Revision ID: e96989d251e8
Revises: 492ec352a608
Create Date: 2020-01-26 20:04:45.224418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e96989d251e8'
down_revision = '492ec352a608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image', sa.String(length=120), nullable=False))
    op.drop_index('images', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['image'])
    op.drop_column('projects', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('images', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('images', 'projects', ['images'], unique=True)
    op.drop_column('projects', 'image')
    # ### end Alembic commands ###
